### ISSUE TITLE
Levantamento de requisitos funcionais

### ISSUE THREAD

**Issue by thaislba** [ES-UFABC/Grupo-1.10#5]

**Comment by thaislba** [comment]
Logar e autenticar usuários
Permitir cadastro de seus pets
Interação entre usuários
- Mensagens diretas
- Comentários em posts

**Comment by acruzf** [comment]
v2
Logar e autenticar usuários
Permitir cadastro de seus pets
Home com cadastros de pet ordenados pelo cadastro de pet perdido mais recente
